### ISSUE TITLE
ImportError: cannot import name 'LinearNDInterpolator'

### ISSUE THREAD

**Issue by 562794175** [kvfrans/variational-autoencoder#9]
Hi,when i run this code ,i got error!

/root/miniconda3/bin/python /root/PycharmProjects/variational-autoencoder/main.py
Traceback (most recent call last):
  File "/root/PycharmProjects/variational-autoencoder/main.py", line 6, in <module>
    from scipy.misc import imsave as ims
  File "/root/miniconda3/lib/python3.6/site-packages/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/root/miniconda3/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 187, in <module>
    from .ndgriddata import *
  File "/root/miniconda3/lib/python3.6/site-packages/scipy/interpolate/ndgriddata.py", line 10, in <module>
    from .interpnd import LinearNDInterpolator, NDInterpolatorBase, \
ImportError: cannot import name 'LinearNDInterpolator'

How can i fix this?

**Comment by 562794175** [comment]
Mybe it is has some problem of my computer envionment ,at last this problem disappeared!

**Comment by esa-prakasa** [comment]
I got the same problem, no answer yet..
